[tool.black]
line-length = 100
target-version = ["py311"]
skip-string-normalization = true
extend-exclude = '''
(
  ^backtests/train_ai_model\.py$
  | ^live_trader_clean_alternative\.py$
  | ^retrain_lstm_balanced\.py$
  | ^live_runner\.py$
  | ^live_trader_clean_final\.py$
  | ^live_trader_clean_fixed\.py$
  | ^live_trader_clean_fixed_syntax\.py$
)
'''

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.ruff]
line-length = 100
target-version = "py311"
select = ["E","F","B","I","UP","ARG","C90"]
ignore = ["E501"]
fix = true
unsafe-fixes = false

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
strict = false
warn_unused_ignores = true
warn_redundant_casts = true
warn_return_any = true
no_implicit_optional = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
exclude = [
    "tests/.*",
    "^config\\.py$",              # exclude top-level config.py
    "^mrben/.*",                  # exclude legacy duplicate package
]

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["tests"]
