app:
  mode: pro
  symbol: XAUUSD.PRO
  timeframe: M15
  bars: 600
  magic: 20250721

strategy:
  core: "sma_cross"
  lookback:
    fast: 20
    slow: 50
  price_action:
    enabled: true
    min_score: 0.60
    patterns: [ENGULF, PIN, INSIDE, SWEEP]
  ml_filter:
    enabled: true
    model_path: "models/ml_filter_v1.onnx"
    min_proba: 0.62
  lstm_filter:
    enabled: true
    model_path: "models/lstm_dir_v1.onnx"
    agree_min: 0.60

confidence:
  base: 0.70
  dynamic:
    regime: {"low_vol": 1.10, "normal": 1.00, "high_vol": 0.85}
    session: {"asia": 0.90, "london": 1.05, "ny": 1.00}
    drawdown: {"calm": 1.00, "mild_dd": 0.90, "deep_dd": 0.80}
  threshold:
    min: 0.68
    max: 0.90

atr:
  sl_mult: 1.6
  tp_r:
    tp1: 0.8
    tp2: 1.5

risk_management:
  base_r_pct: 0.0005     # 0.05% per trade
  min_lot: 0.01
  max_lot: 1.00
  gates:
    spread_max_pts: 120
    exposure_max_positions: 1
    daily_loss_pct: 0.008   # 0.8%
    consecutive_min: 1
    cooldown_sec: 180

session:
  enabled: true
  asia: "A+ only"    # محدودکننده
  london: "normal"
  newyork: "normal"

position_management:
  tp_split:
    enabled: true
    tp1_r: 0.8
    tp2_r: 1.5
    tp1_share: 0.5
    breakeven_after_tp1: true
  trailing:
    enabled: true
    step_points: 50
    buffer_points: 20

order_management:
  default_filling_mode: "ioc"
  max_slippage_pts: 50
  retry_count: 3
  retry_delay: 1.0

metrics:
  port: 8765
  enabled: true

emergency_stop:
  enabled: true
  halt_file_path: "halt.flag"
  check_interval: 1.0
  auto_recovery: false
  recovery_delay: 300.0
  monitoring_enabled: true
  log_all_checks: false

logging:
  level: "INFO"

# Legacy fields for backward compatibility
gates:
  spread_max_pts: 120
  consecutive_base: 1
  cooldown_sec: 180
  session:
    asia: "A+ only"
    london: "normal"
    newyork: "normal"

ab_test:
  enabled: true
  control: "sma_only"
  pro: "ensemble_full"
  paper_broker_latency_ms: [20, 80]

agent:
  enabled: true
  mode: guard
  error_rate_halt_per_min: 5

execution:
  deviation_points: 200
  filling_policy: "adaptive"
